* Nexo Income Tracker

  An [[https://www.electronjs.org/][Electron]] app to help calculate cost-basis, income, and profit from crypto transactions on [[https://www.electronjs.org/][Nexo]].

  This is equal parts "useful tool" and a learning sandbox for me to better understand building an app using Electron.

  Because I'd like to also learn some addition tooling, especially [[https://tailwindcss.com/][TailwindCSS]], I've forked the [[https://github.com/Sanan4li/React-Electron-TailwindCSS-Boilerplate.git][React-Electron-TailwindCSS-Boilerplate]] repo so that I have at least one opinionated starting point.

* Tasks
** DONE Load a Nexo CSV Export into the renderer
   CLOSED: [2021-11-16 Tue 17:30]
   :LOGBOOK:
   - State "DONE"       from "TODO"       [2021-11-16 Tue 17:30]
   :END:
   - It's awesome when an upstream project helps. I learned a bit while trying to handle my own form submission. At the end of the day, the [[https://github.com/nzambello/react-csv-reader][react-csv-reader]] project abstracts a bunch of things for a clean DX!
** TODO Write a journal to a =.ledger= file
** TODO Calculate Cost Basis of assets
** TODO Calculate Income of Assets
** TODO Calculate Profit of Asset Sales
** TODO Option to read from a =.ledger= file on disk
